### ISSUE TITLE
Cannt install hebspacy

### ISSUE THREAD

**Issue by colingoldberg** [8400TheHealthNetwork/HebSpacy#4]
On my Macbook Pro (macos ventura 13.4) I am not able to install hebspacy (or he_ner_news_trf-3.2.1-py3-none-any.whl).

I recently installed spacy, and also the rust compiler. If I run:
$ pip3 install -U hebspacy

the last few lines of output are:
ERROR: Failed building wheel for sentencepiece
  Running setup.py clean for sentencepiece
  Building wheel for tokenizers (pyproject.toml) ... done
  Created wheel for tokenizers: filename=tokenizers-0.12.1-cp311-cp311-macosx_13_0_universal2.whl size=3917754 sha256=1283867478c19ccc1f5b57611efd5d7fb4203aea519125abf74bfa3b78c5e522
  Stored in directory: /Users/colingoldberg/Library/Caches/pip/wheels/7f/24/a6/0645b49cb6ffa12e02d9841bc0f190b7ccaeecb8c09bf1dc32
Successfully built tokenizers
Failed to build sentencepiece
ERROR: Could not build wheels for sentencepiece, which is required to install pyproject.toml-based projects

If I run:
$ pip3 list

hebspacy does not show up.

Thank you for your attention.

Colin Goldberg

**Comment by JeredBlu** [comment]
@colingoldberg Any luck on this? ive been stuck for a few days with the same problem

**Comment by Esthersh** [comment]
I’m encountering the same issue, @colingoldberg @JrodbTG. Have there been any solutions or PRs related to this?

**Comment by colingoldberg** [comment]
Is this repo being maintained? Today I once again tried "pip install hebspacy", and got the following error (sorry, but it is long):

Collecting hebspacy
  Downloading hebspacy-0.1.7-py3-none-any.whl.metadata (4.9 kB)
Collecting sentencepiece==0.1.96 (from hebspacy)
  Downloading sentencepiece-0.1.96.tar.gz (508 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting spacy-transformers (from hebspacy)
  Downloading spacy_transformers-1.4.0-cp313-cp313-macosx_11_0_arm64.whl.metadata (7.0 kB)
Collecting spacy==3.2.2 (from hebspacy)
  Downloading spacy-3.2.2.tar.gz (1.1 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.1/1.1 MB 8.7 MB/s  0:00:00
  Installing build dependencies ... error
  error: subprocess-exited-with-error
  
  × installing build dependencies for spacy did not run successfully.
  │ exit code: 1
  ╰─> [556 lines of output]
      Collecting setuptools
        Using cached setuptools-84.0.0-py3-none-any.whl.metadata (6.6 kB)
      Collecting cython<3.0,>=0.25
        Downloading Cython-0.29.37-py2.py3-none-any.whl.metadata (3.1 kB)
      Collecting cymem<2.1.0,>=2.0.2
        Downloading cymem-2.0.13-cp313-cp313-macosx_11_0_arm64.whl.metadata (9.7 kB)
      Collecting preshed<3.1.0,>=3.0.2
        Downloading preshed-3.0.13-cp313-cp313-macosx_11_0_arm64.whl.metadata (5.2 kB)
      Collecting murmurhash<1.1.0,>=0.28.0
        Downloading murmurhash-1.0.15-cp313-cp313-macosx_11_0_arm64.whl.metadata (2.3 kB)
      Collecting thinc<8.1.0,>=8.0.12
        Downloading thinc-8.0.17.tar.gz (189 kB)
        Installing build dependencies: started
        Installing build dependencies: finished with status 'error'
        error: subprocess-exited-with-error
      
        × installing build dependencies for thinc did not run successfully.
        │ exit code: 1
        ╰─> [533 lines of output]
            Collecting setuptools
              Using cached setuptools-84.0.0-py3-none-any.whl.metadata (6.6 kB)
            Collecting cython<3.0,>=0.25
              Using cached Cython-0.29.37-py2.py3-none-any.whl.metadata (3.1 kB)
            Collecting murmurhash<1.1.0,>=1.0.2
              Using cached murmurhash-1.0.15-cp313-cp313-macosx_11_0_arm64.whl.metadata (2.3 kB)
            Collecting cymem<2.1.0,>=2.0.2
              Using cached cymem-2.0.13-cp313-cp313-macosx_11_0_arm64.whl.metadata (9.7 kB)
            Collecting preshed<3.1.0,>=3.0.2
              Using cached preshed-3.0.13-cp313-cp313-macosx_11_0_arm64.whl.metadata (5.2 kB)
            Collecting blis<0.8.0,>=0.4.0
              Downloading blis-0.7.11.tar.gz (2.9 MB)
                 ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.9/2.9 MB 10.1 MB/s  0:00:00
              Installing build dependencies: started
              Installing build dependencies: finished with status 'done'
              Getting requirements to build wheel: started
              Getting requirements to build wheel: finished with status 'error'
              error: subprocess-exited-with-error
      
              × Getting requirements to build wheel did not run successfully.
              │ exit code: 1
              ╰─> [507 lines of output]
      
                  Error compiling Cython file:
                  ------------------------------------------------------------
                  ...
                  #
                  # See __init__.cython-30.pxd for the real Cython header
                  #
      
                  # intentionally created compiler error that only triggers on Cython < 3.0.0
                  DEF err = int('Build aborted: the NumPy Cython headers require Cython 3.0.0 or newer.')
                              ^
                  ------------------------------------------------------------
      
                  /private/var/folders/0m/k09v1ftd4kx2k53b45gwpn1r0000gn/T/pip-build-env-ekkkfe83/overlay/lib/python3.13/site-packages/numpy/__init__.pxd:12:13: Error in compile-time expression: ValueError: invalid literal for int() with base 10: 'Build aborted: the NumPy Cython headers require Cython 3.0.0 or newer.'
      
      
                  Error compiling Cython file:
                  ------------------------------------------------------------
                  ...
                  from .cy cimport const_double1d_t, const_double2d_t
      
                  import numpy
      
      
                  def axpy(const_reals1d_ft A, double scale=1., np.ndarray out=None):
                                                               ^
                  ------------------------------------------------------------
      
                  blis/py.pyx:12:46: 'ndarray' is not a type identifier
      
                  Error compiling Cython file:
                  ------------------------------------------------------------
                  ...
                      else:
                          B = NULL
                          raise TypeError("Unhandled fused type")
      
      
                  def batch_axpy(reals2d_ft A, reals1d_ft B, np.ndarray out=None):
                                                            ^
                  ------------------------------------------------------------
      
                  blis/py.pyx:30:43: 'ndarray' is not a type identifier
      
                  Error compiling Cython file:
                  ------------------------------------------------------------
                  ...
      
                  def batch_axpy(reals2d_ft A, reals1d_ft B, np.ndarray out=None):
                      pass
      
      
                  def ger(const_reals2d_ft A, const_reals1d_ft B, double scale=1., np.ndarray out=None):
                                                                                  ^
                  ------------------------------------------------------------
      
                  blis/py.pyx:34:65: 'ndarray' is not a type identifier
      
                  Error compiling Cython file:
                  ------------------------------------------------------------
                  ...
                          C = NULL
                          raise TypeError("Unhandled fused type")
      
      
                  def gemm(const_reals2d_ft A, const_reals2d_ft B,
                           np.ndarray out=None, bint trans1=False, bint trans2=False,
                          ^
                  ------------------------------------------------------------
      
                  blis/py.pyx:65:9: 'ndarray' is not a type identifier
      
                  Error compiling Cython file:
                  ------------------------------------------------------------
                  ...
                          C = NULL
                          raise TypeError("Unhandled fused type")
      
                  def gemv(const_reals2d_ft A, const_reals1d_ft B,
                          bint trans1=False, double alpha=1., double beta=1.,
                          np.ndarray out=None):
                         ^
                  ------------------------------------------------------------
      
                  blis/py.pyx:115:8: 'ndarray' is not a type identifier
      
                  Error compiling Cython file:
                  ------------------------------------------------------------
                  ...
      
                  def axpy(const_reals1d_ft A, double scale=1., np.ndarray out=None):
                      if const_reals1d_ft is const_float1d_t:
                          if out is None:
                              out = numpy.zeros((A.shape[0],), dtype='f')
                          B = <float*>out.data
                             ^
                  ------------------------------------------------------------
      
                  blis/py.pyx:16:12: Python objects cannot be cast to pointers of primitive types
      
                  Error compiling Cython file:
                  ------------------------------------------------------------
                  ...
                          B = <float*>out.data
                          return out
                      elif const_reals1d_ft is const_double1d_t:
                          if out is None:
                              out = numpy.zeros((A.shape[0],), dtype='d')
                          B = <double*>out.data
                             ^
                  ------------------------------------------------------------
      
                  blis/py.pyx:21:12: Python objects cannot be cast to pointers of primitive types
      
                  Error compiling Cython file:
                  ------------------------------------------------------------
                  ...
                                  cy.NO_CONJUGATE, cy.NO_CONJUGATE,
                                  A.shape[0], B.shape[0],
                                  scale,
                                  &A[0,0], 1,
                                  &B[0], 1,
                                  <float*>out.data, out.shape[1], 1)
                                 ^
                  ------------------------------------------------------------
      
                  blis/py.pyx:45:16: Python objects cannot be cast to pointers of primitive types
      
                  Error compiling Cython file:
                  ------------------------------------------------------------
                  ...
                  def ger(const_reals2d_ft A, const_reals1d_ft B, double scale=1., np.ndarray out=None):
                      if const_reals2d_ft is const_float2d_t and const_reals1d_ft is const_float1d_t:
                          if out is None:
                              out = numpy.zeros((A.shape[0], B.shape[0]), dtype='f')
                          with nogil:
                              cy.ger(
                                   ^
                  ------------------------------------------------------------
      
                  blis/py.pyx:39:18: no suitable method found
      
                  Error compiling Cython file:
                  ------------------------------------------------------------
                  ...
                                  cy.NO_CONJUGATE, cy.NO_CONJUGATE,
                                  A.shape[0], B.shape[0],
                                  scale,
                                  &A[0,0], 1,
                                  &B[0], 1,
                                  <double*>out.data, out.shape[1], 1)
                                 ^
                  ------------------------------------------------------------
      
                  blis/py.pyx:57:16: Python objects cannot be cast to pointers of primitive types
      
                  Error compiling Cython file:
                  ------------------------------------------------------------
                  ...
                          return out
                      elif const_reals2d_ft is const_double2d_t and const_reals1d_ft is const_double1d_t:
                          if out is None:
                              out = numpy.zeros((A.shape[0], B.shape[0]), dtype='d')
                          with nogil:
                              cy.ger(
                                   ^
                  ------------------------------------------------------------
      
                  blis/py.pyx:51:18: no suitable method found
      
                  Error compiling Cython file:
                  ------------------------------------------------------------
                  ...
                          if out is None:
                              if beta == 0.:
                                  out = numpy.empty((nM, nN), dtype='f')
                              else:
                                  out = numpy.zeros((nM, nN), dtype='f')
                          C = <float*>out.data
                             ^
                  ------------------------------------------------------------
      
                  blis/py.pyx:82:12: Python objects cannot be cast to pointers of primitive types
      
                  Error compiling Cython file:
                  ------------------------------------------------------------
                  ...
                                  out = numpy.empty((nM, nN), dtype='f')
                              else:
                                  out = numpy.zeros((nM, nN), dtype='f')
                          C = <float*>out.data
                          with nogil:
                              cy.gemm(
                                    ^
                  ------------------------------------------------------------
      
                  blis/py.pyx:84:19: no suitable method found
      
                  Error compiling Cython file:
                  ------------------------------------------------------------
                  ...
                                  C, out.shape[1], 1)
                          return out
                      elif const_reals2d_ft is const_double2d_t:
                          if out is None:
                              out = numpy.zeros((A.shape[0], B.shape[1]), dtype='d')
                          C = <double*>out.data
                             ^
                  ------------------------------------------------------------
      
                  blis/py.pyx:97:12: Python objects cannot be cast to pointers of primitive types
      
                  Error compiling Cython file:
                  ------------------------------------------------------------
                  ...
                      elif const_reals2d_ft is const_double2d_t:
                          if out is None:
                              out = numpy.zeros((A.shape[0], B.shape[1]), dtype='d')
                          C = <double*>out.data
                          with nogil:
                              cy.gemm(
                                    ^
                  ------------------------------------------------------------
      
                  blis/py.pyx:99:19: no suitable method found
      
                  Error compiling Cython file:
                  ------------------------------------------------------------
                  ...
                                  A.shape[0], A.shape[1],
                                  alpha,
                                  &A[0,0], A.shape[1], 1,
                                  &B[0], 1,
                                  beta,
                                  <float*>out.data, 1)
                                 ^
                  ------------------------------------------------------------
      
                  blis/py.pyx:128:16: Python objects cannot be cast to pointers of primitive types
      
                  Error compiling Cython file:
                  ------------------------------------------------------------
                  ...
                                  A.shape[0], A.shape[1],
                                  alpha,
                                  &A[0,0], A.shape[1], 1,
                                  &B[0], 1,
                                  beta,
                                  <double*>out.data, 1)
                                 ^
                  ------------------------------------------------------------
      
                  blis/py.pyx:142:16: Python objects cannot be cast to pointers of primitive types
      
                  Error compiling Cython file:
                  ------------------------------------------------------------
                  ...
                  def ger(const_reals2d_ft A, const_reals1d_ft B, double scale=1., np.ndarray out=None):
                      if const_reals2d_ft is const_float2d_t and const_reals1d_ft is const_float1d_t:
                          if out is None:
                              out = numpy.zeros((A.shape[0], B.shape[0]), dtype='f')
                          with nogil:
                              cy.ger(
                               ^
                  ------------------------------------------------------------
      
                  blis/py.pyx:39:14: Invalid use of fused types, type cannot be specialized
      
                  Error compiling Cython file:
                  ------------------------------------------------------------
                  ...
                          return out
                      elif const_reals2d_ft is const_double2d_t and const_reals1d_ft is const_double1d_t:
                          if out is None:
                              out = numpy.zeros((A.shape[0], B.shape[0]), dtype='d')
                          with nogil:
                              cy.ger(
                               ^
                  ------------------------------------------------------------
      
                  blis/py.pyx:51:14: Invalid use of fused types, type cannot be specialized
      
                  Error compiling Cython file:
                  ------------------------------------------------------------
                  ...
                                  out = numpy.empty((nM, nN), dtype='f')
                              else:
                                  out = numpy.zeros((nM, nN), dtype='f')
                          C = <float*>out.data
                          with nogil:
                              cy.gemm(
                               ^
                  ------------------------------------------------------------
      
                  blis/py.pyx:84:14: Invalid use of fused types, type cannot be specialized
      
                  Error compiling Cython file:
                  ------------------------------------------------------------
                  ...
                      elif const_reals2d_ft is const_double2d_t:
                          if out is None:
                              out = numpy.zeros((A.shape[0], B.shape[1]), dtype='d')
                          C = <double*>out.data
                          with nogil:
                              cy.gemm(
                               ^
                  ------------------------------------------------------------
      
                  blis/py.pyx:99:14: Invalid use of fused types, type cannot be specialized
      
                  Error compiling Cython file:
                  ------------------------------------------------------------
                  ...
                                  cy.NO_CONJUGATE, cy.NO_CONJUGATE,
                                  A.shape[0], B.shape[0],
                                  scale,
                                  &A[0,0], 1,
                                  &B[0], 1,
                                  <float*>out.data, out.shape[1], 1)
                                            ^
                  ------------------------------------------------------------
      
                  blis/py.pyx:45:27: Accessing Python attribute not allowed without gil
      
                  Error compiling Cython file:
                  ------------------------------------------------------------
                  ...
                                  cy.NO_CONJUGATE, cy.NO_CONJUGATE,
                                  A.shape[0], B.shape[0],
                                  scale,
                                  &A[0,0], 1,
                                  &B[0], 1,
                                  <float*>out.data, out.shape[1], 1)
                                                            ^
                  ------------------------------------------------------------
      
                  blis/py.pyx:45:43: Indexing Python object not allowed without gil
      
                  Error compiling Cython file:
                  ------------------------------------------------------------
                  ...
                                  cy.NO_CONJUGATE, cy.NO_CONJUGATE,
                                  A.shape[0], B.shape[0],
                                  scale,
                                  &A[0,0], 1,
                                  &B[0], 1,
                                  <float*>out.data, out.shape[1], 1)
                                                      ^
                  ------------------------------------------------------------
      
                  blis/py.pyx:45:37: Accessing Python attribute not allowed without gil
      
                  Error compiling Cython file:
                  ------------------------------------------------------------
                  ...
                                  cy.NO_CONJUGATE, cy.NO_CONJUGATE,
                                  A.shape[0], B.shape[0],
                                  scale,
                                  &A[0,0], 1,
                                  &B[0], 1,
                                  <double*>out.data, out.shape[1], 1)
                                             ^
                  ------------------------------------------------------------
      
                  blis/py.pyx:57:28: Accessing Python attribute not allowed without gil
      
                  Error compiling Cython file:
                  ------------------------------------------------------------
                  ...
                                  cy.NO_CONJUGATE, cy.NO_CONJUGATE,
                                  A.shape[0], B.shape[0],
                                  scale,
                                  &A[0,0], 1,
                                  &B[0], 1,
                                  <double*>out.data, out.shape[1], 1)
                                                             ^
                  ------------------------------------------------------------
      
                  blis/py.pyx:57:44: Indexing Python object not allowed without gil
      
                  Error compiling Cython file:
                  ------------------------------------------------------------
                  ...
                                  cy.NO_CONJUGATE, cy.NO_CONJUGATE,
                                  A.shape[0], B.shape[0],
                                  scale,
                                  &A[0,0], 1,
                                  &B[0], 1,
                                  <double*>out.data, out.shape[1], 1)
                                                       ^
                  ------------------------------------------------------------
      
                  blis/py.pyx:57:38: Accessing Python attribute not allowed without gil
      
                  Error compiling Cython file:
                  ------------------------------------------------------------
                  ...
                                  nM, nN, nK,
                                  alpha,
                                  &A[0,0], A.shape[1], 1,
                                  &B[0,0], B.shape[1], 1,
                                  beta,
                                  C, out.shape[1], 1)
                                             ^
                  ------------------------------------------------------------
      
                  blis/py.pyx:92:28: Indexing Python object not allowed without gil
      
                  Error compiling Cython file:
                  ------------------------------------------------------------
                  ...
                                  nM, nN, nK,
                                  alpha,
                                  &A[0,0], A.shape[1], 1,
                                  &B[0,0], B.shape[1], 1,
                                  beta,
                                  C, out.shape[1], 1)
                                       ^
                  ------------------------------------------------------------
      
                  blis/py.pyx:92:22: Accessing Python attribute not allowed without gil
      
                  Error compiling Cython file:
                  ------------------------------------------------------------
                  ...
                                  A.shape[0], B.shape[1], A.shape[1],
                                  alpha,
                                  &A[0,0], A.shape[1], 1,
                                  &B[0,0], B.shape[1], 1,
                                  beta,
                                  C, out.shape[1], 1)
                                             ^
                  ------------------------------------------------------------
      
                  blis/py.pyx:107:28: Indexing Python object not allowed without gil
      
                  Error compiling Cython file:
                  ------------------------------------------------------------
                  ...
                                  A.shape[0], B.shape[1], A.shape[1],
                                  alpha,
                                  &A[0,0], A.shape[1], 1,
                                  &B[0,0], B.shape[1], 1,
                                  beta,
                                  C, out.shape[1], 1)
                                       ^
                  ------------------------------------------------------------
      
                  blis/py.pyx:107:22: Accessing Python attribute not allowed without gil
      
                  Error compiling Cython file:
                  ------------------------------------------------------------
                  ...
                                  A.shape[0], A.shape[1],
                                  alpha,
                                  &A[0,0], A.shape[1], 1,
                                  &B[0], 1,
                                  beta,
                                  <float*>out.data, 1)
                                            ^
                  ------------------------------------------------------------
      
                  blis/py.pyx:128:27: Accessing Python attribute not allowed without gil
      
                  Error compiling Cython file:
                  ------------------------------------------------------------
                  ...
                                  A.shape[0], A.shape[1],
                                  alpha,
                                  &A[0,0], A.shape[1], 1,
                                  &B[0], 1,
                                  beta,
                                  <double*>out.data, 1)
                                             ^
                  ------------------------------------------------------------
      
                  blis/py.pyx:142:28: Accessing Python attribute not allowed without gil
                  BLIS_COMPILER? None
                  Compiling blis/cy.pyx because it changed.
                  Compiling blis/py.pyx because it changed.
                  [1/2] Cythonizing blis/cy.pyx
                  [2/2] Cythonizing blis/py.pyx
                  Traceback (most recent call last):
                    File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 389, in <module>
                      main()
                      ~~~~^^
                    File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 373, in main
                      json_out["return_val"] = hook(**hook_input["kwargs"])
                                               ~~~~^^^^^^^^^^^^^^^^^^^^^^^^
                    File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 143, in get_requires_for_build_wheel
                      return hook(config_settings)
                    File "/private/var/folders/0m/k09v1ftd4kx2k53b45gwpn1r0000gn/T/pip-build-env-ekkkfe83/overlay/lib/python3.13/site-packages/setuptools/build_meta.py", line 333, in get_requires_for_build_wheel
                      return self._get_build_requires(config_settings, requirements=[])
                             ~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                    File "/private/var/folders/0m/k09v1ftd4kx2k53b45gwpn1r0000gn/T/pip-build-env-ekkkfe83/overlay/lib/python3.13/site-packages/setuptools/build_meta.py", line 301, in _get_build_requires
                      self.run_setup()
                      ~~~~~~~~~~~~~~^^
                    File "/private/var/folders/0m/k09v1ftd4kx2k53b45gwpn1r0000gn/T/pip-build-env-ekkkfe83/overlay/lib/python3.13/site-packages/setuptools/build_meta.py", line 317, in run_setup
                      exec(code, locals())  # noqa: S102 # exec is intentional here
                      ~~~~^^^^^^^^^^^^^^^^
                    File "<string>", line 305, in <module>
                    File "/private/var/folders/0m/k09v1ftd4kx2k53b45gwpn1r0000gn/T/pip-build-env-ekkkfe83/overlay/lib/python3.13/site-packages/Cython/Build/Dependencies.py", line 1115, in cythonize
                      cythonize_one(*args)
                      ~~~~~~~~~~~~~^^^^^^^
                    File "/private/var/folders/0m/k09v1ftd4kx2k53b45gwpn1r0000gn/T/pip-build-env-ekkkfe83/overlay/lib/python3.13/site-packages/Cython/Build/Dependencies.py", line 1238, in cythonize_one
                      raise CompileError(None, pyx_file)
                  Cython.Compiler.Errors.CompileError: blis/py.pyx
                  [end of output]
      
              note: This error originates from a subprocess, and is likely not a problem with pip.
            ERROR: Failed to build 'blis' when getting requirements to build wheel
            [end of output]
      
        note: This error originates from a subprocess, and is likely not a problem with pip.
      ERROR: Failed to build 'thinc' when installing build dependencies for thinc
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
ERROR: Failed to build 'spacy' when installing build dependencies for spacy
